import type { Metadata } from "next";
import AuthProvider from "./AuthProvider";
import "./globals.css";
import Navbar from "@/components/Navbar";
import MainContentWrapper from "@/components/MainContentWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <MainContentWrapper>{children}</MainContentWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
